name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore -o launcher

    - name: Zip build
      uses: papeloto/action-zip@v1
      with:
        files: launcher/
        dest: result.zip

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: result.zip
    #- name: Test
    #  run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"
